### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by Hayabusya** [schindlerd/mwgcs-logpuller-pub#1]
Hi Schindlerd, I noticed that this script only supports Python Version 2. Will there be an upgrade to support Python Version 3?

**Comment by schindlerd** [comment]
Please try out the python3 branch and tell me if it works for you.

**Comment by Hayabusya** [comment]
Thanks for your help.  May I ask what log format you would recommend for extracting logs with this script? The csv format appears to have an error because it is unable to write data into the csv file format.

**Comment by schindlerd** [comment]
> Thanks for your help. May I ask what log format you would recommend for extracting logs with this script? The csv format appears to have an error because it is unable to write data into the csv file format.

The Skyhigh REST API returns this csv format by default. Where do you encounter an error?

When you plan to forward the downloaded data to a centralized Log Management solution you would need to configure a JSON input/drain - as the script transforms the csv to a JSON stream.
